### ISSUE TITLE
Cant manage to show the sensors

### ISSUE THREAD

**Issue by Lejouz** [Marck/home-assistant-blueprints#3]
Thank you for the great blueprint!

I cant manage to show the sensors for which the battery is low in the notification. Whats wrong about my action code?
`action: notify.mobile_app_oneplus_8
metadata: {}
data:
  title: "HA Batterie wechseln. "
  message: "Schaue hier: '{{sensors}}'"`
![grafik](https://github.com/user-attachments/assets/ac8e2b9f-381c-4b98-8b2c-e9c652af64ff)

Thanks for any hint!

**Comment by Marck** [comment]
Hi, thank you for the praise (it's not mine, but I modified it to match my needs).

What is the message it sends? 
I think it doesn't display the correct result because of the single quotes before sensors (`'{{sensors}}'`).
Or you have a high treshold and no entities match. Can you post the rest of your automation?

What I have works like a charm:
```
- service: notify.pushover
   data:
     title: HASS Battery check
     message: |
       <strong>Devices with a battery life below 20%:</strong>
       {{sensors}}
```

**Comment by Lejouz** [comment]
Hey @Marck ,

thank you very much for your reply. I think the mistake was on my side to be honest. 

After configuring the automation I tried test triggering the automation by playing only notify component of it. I received a message on my phone but always without naming the sensors which were empty. After checking the code I realized that {{sensors}} had to be empty because the automation, hence code, of the beginning did not run thorough. Now when I test it again running the entire automation it seems to work like a charm. Havent had a real case yet but I will keep monitoring. 

Thanks for your time!
Best
Julian

**Comment by Marck** [comment]
No worries, glad it worked for you in the end.
Testing the blueprint can be a bit tricky because, what you mentioned, the sensors will be empty.
When I test my automation I reduce my treshold to 90% so I get at least one entity that matches, so you can try doing that when testing.

Good luck with the blueprint, hope it serves you well!
